prices:
  '10 groups':
    month:         99
    half year:      199
    year:          499

  '25 groups':
    month:         199
    half year:      399
    year:          799

  '50 groups':
    month:         599
    half year:      899
    year:          1499

  '100 groups':
    month:         999
    half year:      1299
    year:          2999
